import "@pulsarmoney/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StarknetProvider } from "../providers/starknet-provider";
import { MainLayout } from "../components/main-layout";
import { UIProviders } from "@pulsarmoney/ui/components/ui-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProviders attribute="class" defaultTheme="system" enableSystem>
          <StarknetProvider>
            <MainLayout>{children}</MainLayout>
          </StarknetProvider>
        </UIProviders>
      </body>
    </html>
  );
}
